Add Support For Flatpak Icons
JakeStanger/ironbar pull request #191
Opened 2023-06-16 19:19 UTC by body20002

Fixes #190

2023-06-16 19:53 UTC, JakeStanger requested changes
Hey, thanks for the PR. 

It looks like there's a lot of code in here that isn't relevant to the fix, and some I'm struggling to understand the reasoning behind. Could you remove any changes that aren't needed from the PR please?

It also looks like the build isn't passing at the moment - can you run `cargo fmt` and check for any  `cargo clippy` warnings before re-committing?

If you're able to amend your changes into the single commit that'd be perfect. Could you also change the commit message to fall in line with [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/#summary) to ensure your change is included in the changelog please:

```
fix: not resolving flatpak application icons
```

If you have any questions or want any help let me know :)

2023-06-16 23:22 UTC, body20002 commented
Thanks for replying @JakeStanger
The reason behind changing the implementation in both `get_desktop_icon_name` and `find_desktop_file` is because the current implementation of `find_desktop_file` is too simple to actually get the required icon, it simply tries to look for `app_id.desktop` which flatpak simply doesn't use, flatpak uses `com.company.app.desktop` this can be found in the docs [here](https://docs.flatpak.org/en/latest/conventions.html#application-ids)

and the reason behind changing `get_desktop_icon_name` was it was calling `find_desktop_file` and in each call it'll find all the `.desktop` files and check them, so I moved out the "finding `.desktop` files" part outside and it only checks, I'm planing on improving it further but I don't know much rust and I'm restricted by the compiler.

You may also found that I used `HashMap<String, Vec<String>>` for parsed desktop files that because some apps like `brave` have multiple entry to one attribute like `"Name"` attribute as shown below

```
[Desktop Entry]
Version=1.0
Name=Brave

[Desktop Action new-window]
Name=New Window

[Desktop Action new-private-window]
Name=New Incognito Window
```
_I removed the irrelevant parts_ 

which if you tried with the old implementation you would only get the last one and get no matches with the `app_id`

Another thing is this part you may find it very confusing, same as me
```rust
let icons = desktop_file.get("Icon").into_iter().flatten();
for icon in icons.clone() {
    return Some(icon.to_owned());
}
```
I couldn't come with a cleaner way to do it.
I tried using the `match` statement in `get_desktop_icon_name` but the code was too messy and nested badly so I just used simple `if` statements.

If you have any idea on how to do it please tell me.
I'll make sure next commit will follow the [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/#summary) and run `cargo fmt` and `cargo clippy` before re-committing :)

2023-06-17 15:19 UTC, JakeStanger commented
Thanks for the explanation, that's cleared a lot up. I wasn't aware Flatpak did that. 

I am not going to be able to merge the current implementation for a few reasons I'm afraid, which I've gone into below. I have also included a review of the code as it stands to hopefully give a few pointers.

> I don't know much rust and I'm restricted by the compiler.

Rust is a hard language to learn, but it's a great one to, and I'd love to see more of it. I always appreciate anybody who shows an interest and wants to contribute to the project, so I'd like to keep this open and work with you to get this to where it needs to be. For now, could you mark this as a draft please?

## Implementation Issues

One issue is the code quality, but we can get to that through some refactoring.

The main reason I'm not going to be able to merge this is efficiency; remember this code runs **per image** (assuming it needs to be looked up).

Let's start by looking at my current impl, which I'll admit could be improved upon:

1. The application directories are walked, checking for a match on `app_id` by filename.
2. If a match is found, the file is parsed into a map.
3. The `icon` key is loaded from the map.

And compare that to yours:

1. The application directories are walked, finding every `.desktop` file.
2. Each of these files is then parsed into a map. A map of each file against its parsed map is then created.
3. Every single file is then checked, pulling out an array of all the potentially relevant keys, and checking each one for a match.
4. If a match is found, the path to the file is returned.
5. The returned path is then used to pull out the desktop file map which we just had, and pull out the icon key.

The two big problems here are:

- This causes a *lot* of unnecessary I/O, as this means Ironbar will read hundreds of files multiple times on startup. This will need to fundamentally change.
- The implementation creates a lot of complex data structures only to read the values it just had, then throw them away again. This requires a lot of memory allocation and de-allocation, and can be slow. We should be able to sort this with some refactoring.

---

So how do we go about improving this, given Flatpak's requirement to be difficult and give things their own names?

- Prioritise looking at the file names, and avoid reading the file unless absolutely necessary. This can be done by amending my current check to be a bit broader when walking the directories.
- Use properties other than `app_id` . It just so happens that most of the time this matches up, but a window may have other properties on it, we can grab to help. You may also be able to use some GTK/XDG/Flatpak tool to query the data, or at least get close to it (I've not looked into this, there might not be anything).
- If we really do have to read a file, be more efficient about what we do with it. Instead of converting the whole file to a map, only to throw it away again (I'm guilty of this too!), we can just loop over the keys and only look at the ones we want. Something akin to `if (key == "name" && value == app_id) { return icon }`.
- Cache the results! Rather than building out a map every time an icon is read (which could potentially be the same icon), we could cache these and then check the cache for subsequent runs. This avoids the need to read/parse the same file more than once.

## Code Review

Rust's tricky and different and I get that, so I think it's a useful learning exercise to go over some of the things I've spotted and how you could change those still. I'll keep it inline rather than doing a proper GH review because I think that makes sense in this context. I've given some specific examples in context, but I've not covered everything.

Several of the things I've raised here are actually covered by Clippy. If you run that, it'll point out any shortcomings, give reasons, and offer fixes for you. You can turn on some additional checks too like `cargo clippy -- -W clippy::pedantic` (note you'll probably get a lot of stuff that isn't worth paying attention to across the whole program).

A lot of it comes down to learning about iterators. These are rust's superpower, as they let you do some crazy stuff in one chain, remove a lot of boilerplate code, and are smart enough that the compiler can compile them down into a single loop, so you lose no performance. Iterators are available on lots of types by default, including `Option`, `Result` and just about any collection type.

### `.unwrap()` 

Using `unwrap` is [generally discouraged](https://doc.rust-lang.org/std/option/enum.Option.html#method.unwrap), because where no value is found, it will cause the entire application to panic and exit, and provides little context for users as to why.

In scenarios where crashing is appropriate (ie something has gone *very* wrong internally, and continuing would be bad), you should prefer to use `.expect()` which makes it clear in code and to users what went wrong.

Otherwise, if you would expect the program to carry on and handle a missing value, you should prefer to use `if let` or `match`, or even fall back to a default with something like `unwrap_or`.

In cases where a function returns `Option` or `Result`, you can often use the `?` operator which propagates the error upwards (think of it as unwrap or return).

I've noticed in a few cases, you're checking for an error/none, then unwrapping afterwards - this is logically sound, but it results in the check being done twice - `unwrap()` internally will check if the value is `error` or `none`. 

You can represent this in a slightly cleaner way:

```rs
let entry = match entry {
  Ok(entry) => entry,
  Err(_) => continue, // you may wish to log a warning/error before continuing
}
```

You can also use iterator methods like `.map` and `and_then` to turn `Option<T>` into `Option<TNew>`, meaning you can chain all the work that *should* happen if the value exists, and do nothing if it doesn't. This works for `Result` too.

### `.clone()`

Every call to `clone`* does quite literally take a value in memory and make a full copy of it. Since we're dealing with strings, this means more memory has to be allocated on the heap, and a new pointer assigned on the stack. This can cause the program to ask the OS for memory, which can be slow.

There are scenarios where cloning is required (sometimes you need to consume the data in multiple places). Where you can though, you should try to avoid it and abide by the below:

- Avoid calling the same method multiple times (just good practise in general). For example, all operations you perform on `DirEntry` (`entry`) are done on the underlying path . Your multiple calls to `.into_path` could be replaced with a single variable assignment, removing the need to clone any data.
- Use references where possible. Several methods will work on references anyway, and Rust is smart enough to handle a lot of operations for you. For example `&str == String` is supported, so you can borrow a string value.

The borrow checker is a tricky beast to master, so if you have any problems don't worry too much, we can address those at the end.

* The `Rc` and `Arc` smart pointers are exceptions to this, as they use reference counting and just create a new pointer. Any types that implement `Copy` are also exceptions, since they can be directly assigned on the stack.

### `for { if { return } }`

In cases like these (there's a few variants), we can deploy some  :sparkle: functional programming :sparkle:  Iterators are once again super helpful and let you flatten the code.

For example, take this check:

```rs
for name in names {
    if name.to_lowercase().contains(app_id) {
        return Some(path);
    }
}
```

This could instead be written as:

```rs
if names.any(|name| name.contains(app_id)) { return Some(path); }
```

I would also generally recommend against multiple `returns` in a function. There are cases where it makes sense, as sometimes it just makes it need [...]

2023-06-18 09:08 UTC, body20002 commented
@JakeStanger is it okay to add this [crate](https://docs.rs/cached/latest/cached/)?

2023-06-18 09:41 UTC, body20002 commented
if all is fine I'll squish all the changes into 1 commit

2023-06-18 10:03 UTC, JakeStanger commented
> @JakeStanger is it okay to add this [crate](https://docs.rs/cached/latest/cached/)?

I think it should be possible to do what we need without. You can use [once_cell](https://doc.rust-lang.org/std/cell/struct.OnceCell.html) (added in Rust 1.70) with a hashmap, and just read/write to that either side of the main logic.

2023-06-18 15:11 UTC, body20002 commented
> > @JakeStanger is it okay to add this [crate](https://docs.rs/cached/latest/cached/)?
> 
> I think it should be possible to do what we need without. You can use [once_cell](https://doc.rust-lang.org/std/cell/struct.OnceCell.html) (added in Rust 1.70) with a hashmap, and just read/write to that either side of the main logic.

`OnceCell` is a very different approach and would require changing a lot of the code to make it work but I'll try.

2023-06-18 18:32 UTC, body20002 commented
I forgot to add a way to invalidate the cache in the previous [commit](https://github.com/JakeStanger/ironbar/pull/191/commits/6cee4bbe0388860ca0fbb260d5b49c01b51b4695)

I don't think it's very clean to use OnceCell instead of just using the above [cached](https://docs.rs/cached/latest/cached/) crate

running `cargo clippy` gives me [this](https://rust-lang.github.io/rust-clippy/master/index.html#/declare_interior_mutable_const)
I'm not sure what to do

2023-06-18 19:07 UTC, yavko commented
> running `cargo clippy` gives me [this](https://rust-lang.github.io/rust-clippy/master/index.html#/declare_interior_mutable_const)
> I'm not sure what to do

Switch to a static, when using atomics or mutexes that should always be available use static as const doesn't pass references it copies of the value every time

2023-06-18 19:11 UTC, yavko requested changes

2023-06-18 19:11 UTC, yavko commented on src/desktop_file.rs
> +const DESKTOP_FILES_CELL: OnceCell<HashMap<PathBuf, HashMap<String, Vec<String>>>> =
Replace `const` with `static`

2023-06-18 19:11 UTC, yavko commented on src/desktop_file.rs
> +const ENTRIES_CELL: OnceCell<Vec<DirEntry>> = OnceCell::new();
Replace `const` with `static`

2023-06-18 19:14 UTC, JakeStanger commented
> I don't think it's very clean to use OnceCell instead of just using the above [cached](https://docs.rs/cached/latest/cached/) crate

It's generally good to avoid introducing more dependencies where possible, because they increase the build time, and increase the amount of 3rd party code we rely on. `cached` under the hood just uses `OnceCell`, with some extra stuff we don't need here like memoization. 

> I forgot to add a way to invalidate the cache 

What's your reasoning for needing cache invalidation? In my mind, we should never need to remove anything from the cache, since the .desktop files we're reading can be assumed static for the lifetime of Ironbar (it's only held in memory, so the cache gets emptied when you restart anyway).

2023-06-18 22:16 UTC, body20002 commented
> What's your reasoning for needing cache invalidation? In my mind, we should never need to remove anything from the cache, since the .desktop files we're reading can be assumed static for the lifetime of Ironbar (it's only held in memory, so the cache gets emptied when you restart anyway).
 
 I know that, but from the user pov it would seem like a bug, and I personally wouldn't like restarting ironbar very time I install an app just to get the icons. 
 
 > Replace `const` with `static`
 
when I replace it I get this error message
``` `std::cell::OnceCell<HashMap<PathBuf, HashMap<std::string::String, Vec<std::string::String>>>>` cannot be shared between threads safely the trait `std::marker::Sync` is not implemented for `std::cell::OnceCell<HashMap<PathBuf, HashMap<std::string::String, Vec<std::string::String>>>>`if you want to do aliasing and mutation between multiple threads, use `std::sync::OnceLock` instead shared static variables must have a type that implements `Sync` ```

should I switch to `OnceLock` or what?

> From a quick read through the code, it looks like an improvement, so thanks for your continued work on this. There are still a few things I mentioned in my long post above, but we can go through those in more detail when you're ready.

I wouldn't be able to do it without your guidance :)

2023-06-18 22:26 UTC, JakeStanger commented
> I know that, but from the user pov it would seem like a bug, and I personally wouldn't like restarting ironbar very time I install an app just to get the icons.

That's a fair point.

The issue is we still end up walking multiple dirs per icon. I guess that isn't too bad (so long as the .desktop files themselves are cached for Ironbar's lifetime), and I think any alternative is start going to get tricky, so we'll live with that for now.

> should I switch to OnceLock or what?

I've just been fighting the same thing actually. I think you need to use `OnceLock`, and then have a `Mutex` inside that if you need mutability. If you can't get anywhere with that though, the trusty alternative is `lazy_static`.  I've used it a bit for similar patterns, so there's a few examples of that dotted around the code you should be able to use.

2023-06-19 02:34 UTC, yavko commented
> > should I switch to OnceLock or what?
> 
> I've just been fighting the same thing actually. I think you need to use `OnceLock`, and then have a `Mutex` inside that if you need mutability. If you can't get anywhere with that though, the trusty alternative is `lazy_static`.  I've used it a bit for similar patterns, so there's a few examples of that dotted around the code you should be able to use.

Doesn't `OnceLock` already offer mutability?

2023-06-19 07:49 UTC, JakeStanger commented
> Doesn't OnceLock already offer mutability?

It does, but as far as I could tell you have to declare the static as `mut`, which is unsafe. I'd rather delegate that to a `Mutex` or `RwLock` that handles that for us.

2023-06-19 13:25 UTC, body20002 commented
> The issue is we still end up walking multiple dirs per icon. I guess that isn't too bad (so long as the .desktop files themselves are cached for Ironbar's lifetime), and I think any alternative is start going to get tricky, so we'll live with that for now.

I think it'd be much more efficient to ask the os how many files are in these dirs or the size of these dirs and just cache it but I think it's just the same as walking these dirs

> I've just been fighting the same thing actually. I think you need to use OnceLock, and then have a Mutex inside that if you need mutability. If you can't get anywhere with that though, the trusty alternative is lazy_static. I've used it a bit for similar patterns, so there's a few examples of that dotted around the code you should be able to use.

Interesting, I'll take a look at the source code
___
I also noticed that ironbar uses a more of memory using the `OnceLock` approach instead of using the cached crate about 4.7 MB more and the app overall usage is 140+ MB is that normal?

I don't think my code is calling the more expensive version of `get_desktopfile`

I'm using this to get the memory usage
```bash
sudo ps -eo size,pid,user,command --sort -size | \
    awk '{ hr=$1/1024 ; printf("%13.2f Mb ",hr) } { for ( x=4 ; x<=NF ; x++ ) { printf("%s ",$x) } print "" }' |\
    cut -d "" -f2 | cut -d "-" -f1 | grep 'ironbar'
```
_I found it on stack overflow_

2023-06-19 13:51 UTC, JakeStanger commented
> I think it'd be much more efficient to ask the os how many files are in these dirs or the size of these dirs and just cache it but I think it's just the same as walking these dirs

Feel free to play with this if you want. I'd be interested to know how much of a difference it makes.

--- 

I'd expect memory usage to be higher on a production build, but that is abnormally high (my prod config runs at about 25MB). That said, I would be surprised if this is related unless you are putting *way* too much into the cache. It only needs to contain a map of app id -> icon name, which would be a few bytes of text per entry.

2023-06-19 18:41 UTC, body20002 commented
> Feel free to play with this if you want. I'd be interested to know how much of a difference it makes.

Couldn't find a way unfortunately

> my prod config runs at about 25MB

How did you use the above command?

2023-06-20 21:29 UTC, JakeStanger commented
> Did you use the above command?

I checked using my system monitor. Using the command, it comes out at more like 170Mb so I wouldn't worry. I don't have an in depth enough knowledge of the kernel to understand what's going on there, but it seems fine.

2023-06-25 22:37 UTC, body20002 commented
@JakeStanger I think everything is good and ready to merge

2023-06-26 00:32 UTC, body20002 commented
I have a question, why are we even parsing and looking for desktop icons?
doesn't gtk have a function called `lookup_icon`?
and in gtk4 `lookup_icon` have `fallback` args which we can do something like this

```rust
let icon_path = gtk::IconTheme.lookup_icon(
    app_id, 
    [someother_id_for_app], 
    size, 
    scale, 
    direction, 
    flags)
    .get_file().unwrap().get_path().unwrap()
```

and use this inside the widgets like `launcher` and `tray`

2023-06-26 00:40 UTC, body20002 commented
I know that we in `desktop_file.rs` parse the files because of the app_id
my PR doesn't change the API of `desktop_file.rs` is simply fixes a bug related to flatpak icons

I think It's better if we move to gtk4 and refactor the widgets to use `lookup_icon` instead

2023-06-26 09:36 UTC, JakeStanger commented
> why are we even parsing and looking for desktop icons? doesn't gtk have a function called lookup_icon?

Check the image resolver [here](https://github.com/JakeStanger/ironbar/blob/d121dc3d1e9468a67deb528c35fc3897c3840f77/src/image/provider.rs#L80-L82) - we are using that function. Desktop icons are a last-resort fallback if we're unable to find the image by other means. Sometimes apps use icons that don't match their app_id, or sometimes they use absolute paths to images. In these cases we need to check their .desktop file to find these.

> I think It's better if we move to gtk4 and refactor the widgets to use lookup_icon instead

Refactoring to GTK4 is a huge undertaking that will take a long time, and gtk4-layer-shell is tricky to install right now. I have started this though.

2023-06-26 10:17 UTC, JakeStanger requested changes
This is a lot better than it was - thanks again for your effort so far - but there's still a good number of general code quality issues. I've done a proper review this time to drill down into the specifics. 

Have another read of my big post, especially the bits around iterators, and let me know if you have any questions about any of the bits I've flagged. Once you've got those all resolved, I'll do another review and drill down a bit further.

2023-06-26 10:17 UTC, JakeStanger commented on src/desktop_file.rs
> +    for (path, desktop_file) in desktop_files_map.iter() {
Prefer to use `.find`() rather than `for { if { return } }`

2023-06-26 10:17 UTC, JakeStanger commented on src/desktop_file.rs
> +                desktop_file.insert(key.trim().to_string(), vec![value.trim().to_string()]);
There's a lot of duplicate trim and to_string calls going on here. Please only do these once per value - assign them to variables before the check.

2023-06-26 10:17 UTC, JakeStanger commented on src/desktop_file.rs
> +            let desktop_file = parse_desktop_file(path.clone()).expect("desktop_file");
You might be able to get away with passing a `Path` instead of `PathBuf` to `parse_desktop_file`, which would remove the need to clone.

2023-06-26 10:17 UTC, JakeStanger commented on src/desktop_file.rs
> +            desktop_files_cache.get(&path).expect("desktop_file")
Since `get` takes a reference to `path`, you will still have ownership of it afterwards. This means you could swap these two calls and remove the need to clone.

2023-06-26 10:17 UTC, JakeStanger commented on src/desktop_file.rs
> +    None
```suggestion
    icons.next().map(std::string::ToString::to_string)

2023-06-26 12:55 UTC, body20002 commented on Cargo.toml
> +default = ["http", "config+all", "clipboard", "clock", "music+all", "sys_info", "tray", "upower", "workspaces+all"]
This was `cargo fmt` doing not me.

2023-06-26 12:55 UTC, body20002 commented on src/desktop_file.rs
> +                            & file.file_name().to_string_lossy().ends_with("desktop")
thanks for telling me about that single `&` I didn't notice it before XD

2023-06-26 12:56 UTC, body20002 commented on src/desktop_file.rs
> +        Mutex::new(HashMap::new());
Because we need them in `find_desktop_file_by_filedata` these values are the key to find the correct desktop file if `find_desktop_file_by_filename` failed.

if we want to cache the the resolved icons we just need to cache the output of `get_desktop_icon_name` (i.e. we need another hashmap or modify `DESKTOP_FILES` to `HashMap<AppId, (PathBuf, DesktopFile)>`)

2023-06-26 13:09 UTC, body20002 commented on src/desktop_file.rs
> +            }
Not sure if I fully understand what you want.
won't `filter_map` and `filter` also increase the time complexity?

2023-06-26 13:11 UTC, body20002 commented on src/desktop_file.rs
> +            desktop_files_cache.get(&path).expect("desktop_file")
This is not true because we want the last value, the last statement is a return statement  
instead of cloning the `desktop_file` I chose to do a `get` after `insert` to get the reference value

2023-06-26 14:48 UTC, JakeStanger commented on Cargo.toml
> +default = ["http", "config+all", "clipboard", "clock", "music+all", "sys_info", "tray", "upower", "workspaces+all"]
`cargo fmt` does not touch anything except Rust code

2023-06-26 14:52 UTC, JakeStanger commented on src/desktop_file.rs
> +                                                       // `com.company.app` or `com.app.something`
Oh right I see, I misread this code. I think this could still be problematic - could it end up mis-matching on anything containing `com` for example?

2023-06-26 14:54 UTC, JakeStanger commented on src/desktop_file.rs
> +            }
Nope! Rust iterators are super smart in that they'll compile down to a single loop. 

I'm not a fan of needing to wrap everything inside an `if let`, which could be moved to a `filter_map`. The `if .contains` check could also be put into a `filter`, which is a bit cleaner than having a `continue` right at the top.

2023-06-26 14:57 UTC, JakeStanger commented on src/desktop_file.rs
> +            let desktop_file = parse_desktop_file(path.clone()).expect("desktop_file");
Passing `&PathBuf` is generally recommended against, for the same reasons you should avoid passing `&Vec` or `&String`. What error are you getting? As far as I can see it's only being used for `File::open` which should work fine.

2023-06-26 15:02 UTC, JakeStanger commented
Looks like a few of my review points were wrong, so sorry about that. I'll move this out of draft state though, since the implementation seems to be pretty much there now.

2023-06-26 23:15 UTC, body20002 commented on src/desktop_file.rs
> +                                                       // `com.company.app` or `com.app.something`
I don't think any app have the id of `com` or something like `app.com` and if we had `app.com` we would properly catch it in the first check not having to go through the split part (the desktop file would properly have `app.com` in it's name)

if the function returned the wrong path it would be very rare and I think it's better to leave it like this until someone report it so we can make finer adjustment

2023-06-26 23:43 UTC, body20002 commented on src/desktop_file.rs
> +            let desktop_file = parse_desktop_file(path.clone()).expect("desktop_file");
> Passing &PathBuf is generally recommended against, for the same reasons you should avoid passing &Vec or &String.

Interesting, may I ask why? and how do I do it without the use of clone? since I moved to `&Vec` and `&PathBuf` due to cloning.

> What error are you getting?

nvm I was doing `Path` instead of `&Path`

2023-06-27 09:21 UTC, JakeStanger requested changes
I think we're nearly there :)

So the one thing I have noticed that I think should change to try and further reduce IO:

Currently you are reading/parsing EVERY desktop file, then checking through all of these for a match.

It'd be a lot cheaper to read/parse and check for a match in one go, so you only need to read/parse as many files as it takes to get there. 

So I think something akin to this should work:

```rs
files
  .map(parse_desktop_file) // check & add to cache here
  .find(is_match) // check the parsed file keys here
```

2023-06-27 09:21 UTC, JakeStanger commented on src/desktop_file.rs
> +                            .ends_with("desktop")
This check is very long and the nesting getting quite deep. Could it be moved out into its own func please?

2023-06-27 09:21 UTC, JakeStanger commented on src/desktop_file.rs
> +    for file in files {
This could be changed to use `files.find()` to avoid the need for `has_match` and needing two returns

2023-06-27 09:21 UTC, JakeStanger commented on src/desktop_file.rs
> +    });
Here you could map to get the path inline:

```suggestion
    desktop_files_map.iter().find(|(_, desktop_file)| {
        desktop_file
            .values()
            .flatten()
            .any(|value| value.to_lowercase().contains(app_id))
    })
    .map(|(path, _)| path.to_owned())
```

Then remove the `match` underneath.

2023-06-27 09:21 UTC, JakeStanger commented on src/desktop_file.rs
> +        _ => return None, // maybe log here
Definitely good to add a log here so any IO errors can be seen. I'd say a `warn` is probably suitable?

2023-06-29 13:38 UTC, body20002 commented on src/desktop_file.rs
> +                            .ends_with("desktop")
it is in its own function `find_desktop_files`

2023-06-29 16:20 UTC, JakeStanger commented
If you can get that last change done, then squash your changes down, I reckon we're good to get this merged!

2023-06-29 18:24 UTC, body20002 commented
@JakeStanger Done

2023-06-29 18:46 UTC, JakeStanger commented
The build is failing because it's been rebased onto a broken version of master, which I'm pretty sure is my fault. I'm going to try and fix that for you and make a couple of final refactors that clippy's pedantic mode has detected, then I should be able to merge.

2023-06-29 18:47 UTC, JakeStanger approved these changes

2023-06-29 21:46 UTC, JakeStanger commented
I found & fixed a bug in the parse_desktop_file code where it was not actually reading files. I've changed it from using a buffered reader to just `fs::read_to_string`. The iterator code there was also a little more complex than it needed to be, so I've rejigged it a bit to flatten it.

I also removed `-` from the list of characters to split on when looking for a partial match on the filename, since it caused some invalid matches - for example my `jetbrans-pycharm` IDE was getting the `jetbrains-toolbox` icon since it matched on `jetbrains`. There may be a need to remove other chars, but I'll wait for bug reports before doing that and at least we'll know where to look :P

Clippy also flagged up a couple of other bits related to simplifying closures and stuff like that, nothing too notable.

2023-06-29 22:06 UTC, JakeStanger commented
Thanks again for all your work on this :)

2023-06-29 22:06 UTC, merged