Find Additional Applications dirs in XDG_DATA_DIR
JakeStanger/ironbar pull request #210
Opened 2023-07-01 06:35 UTC by christoph00

Applications installed via the Home Manager on Nixos are missing icons on the taskbar.  This patch searches for additional application paths using the XDG_DATA_DIR environment variable.

2023-07-01 08:49 UTC, yavko commented on src/desktop_file.rs
> +                 PathBuf::from("/usr/share")]
I'd recommend adding the flatpak dir as support for flatpak was just added in #191

2023-07-01 10:26 UTC, JakeStanger commented on src/desktop_file.rs
> +                 PathBuf::from("/usr/share")]
This adds to that same vec of dirs, so not necessary to add twice

2023-07-01 10:31 UTC, JakeStanger requested changes
Thanks for the fix. 

A couple of bits before this gets merged please:

- Currently this creates a vector for the new dirs jus to join it into the existing vec. Are you able to phase that out, so that:
  -  If it's `Some`, you just keep the iter (don't `collect()`)
  - If it's `None`, you push directly into the `dirs` vec

- Could you please change the commit message to follow [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/#summary), so that the change is included in the changelog? For example `fix: failing to resolve icons with home_manager`. If you push any further changes up please make sure they're squashed into a single commit.

Can you also make sure to `cargo fmt` and fix anything from `cargo clippy` to ensure the build passes?

2023-07-01 11:09 UTC, yavko commented on src/desktop_file.rs
> +                 PathBuf::from("/usr/share")]
Oh yeah I see now, I though it replaced it lol

2023-07-04 11:53 UTC, JakeStanger approved these changes
LGTM, cheers!

2023-07-04 11:53 UTC, merged