[Feature] Add basic bar visibility change to IPC
JakeStanger/ironbar pull request #236
Opened 2023-07-12 22:29 UTC by A-Cloud-Ninja

Adds a `set_visible` IPC command which takes a boolean `visibility` and string `bar_name` fields.
Simultaneously adds a new config `name` option to name each bar individually (defaults to the monitor name)

Behavior as-is will show/hide *every* bar with a given name. e.g, 2 bars both with the name `test` will be shown/hidden if we pass
`{"type":"set_visible","visible"=true,bar_name="test"}`

2023-07-15 13:41 UTC, JakeStanger requested changes
Thanks for the feature! The config `name` addition is especially useful - I actually need to get this merged to get what I'm working on done :)

I've raised Just a few general code quality bits. If you can resolve those for me please, then squash the commit down to follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary), I'll update the docs and get this merged.

Example commit:
`feat(ipc): add commands to get/set bar visibility`

2023-07-15 13:41 UTC, JakeStanger commented on src/bar.rs
> +    info!("Creating bar {}", bar_name);
```suggestion

    win.set_widget_name(&bar_name);
    info!("Creating bar {}", bar_name);
    
```

2023-07-15 13:41 UTC, JakeStanger commented on src/ipc/commands.rs
> +    /// Gets the visibility of windows with the given name.
```suggestion

    /// Get the visibility of windows with the given name.
```

2023-07-15 13:41 UTC, JakeStanger commented on src/ipc/commands.rs
> +    /// multiple windows if multiple windows with the same name exist).
```suggestion
    /// Set the visibility of the specified window(s) with the given name. 
    /// If multiple windows with the same name exist, this will operate on all of them.
```

2023-07-15 13:41 UTC, JakeStanger commented on src/ipc/commands.rs
> +        ///Bar name to target
```suggestion
        /// Bar name to target.
```

2023-07-15 13:41 UTC, JakeStanger commented on src/ipc/commands.rs
> +        /// Bar name to target
```suggestion
        /// Bar name to target.
```

2023-07-15 13:41 UTC, JakeStanger commented on src/ipc/server.rs
> +///gtk::WidgetExt trait
Please remove this line

2023-07-15 13:41 UTC, JakeStanger commented on src/ipc/server.rs
> +                if !found.is_empty() {
```suggestion

                if !found.is_empty() {
```

2023-07-15 13:41 UTC, JakeStanger commented on src/ipc/server.rs
> +                }
Since this is just getting a list of whether each one is visible or not, then only looking for the first record, you could replace the `.filter()` with `.find()`. You could then replace `.map()` with `.any()` to get a single `bool` out.

You can then also just call `.to_string()` straight on the bool, which should eliminate the need for the nested if.

2023-07-15 13:46 UTC, JakeStanger commented on src/ipc/server.rs
> +                    Response::error("Bar not found")
I'm not a big fan of the use of `map()` here because it produces a vector of unit types. Can you see if you can drop both the `map` and `collect`, then just stick in a normal `for` loop inside the `if !is_empty()` pls?

2023-07-15 13:49 UTC, JakeStanger commented on src/config/mod.rs
> +            name: None,
I think every bar should have a name to make the internals a little easier, rather than this being optional.

 The easiest way would be to just use `get_random_usize()` and convert to a string (unless you want to add a `get_random_string`() method...).

2023-07-15 18:16 UTC, yavko commented on src/ipc/server.rs
> +                    Response::error("Bar not found")
Also wouldn't it be better to include the generic in the variable deceleration, for code clarity?

2023-07-15 19:33 UTC, A-Cloud-Ninja commented on src/config/mod.rs
> +            name: None,
Shouldn't this still be optional *in the config* and the bar otherwise generates one? Internally a name is still assigned at the moment.

2023-07-16 13:46 UTC, JakeStanger commented on src/config/mod.rs
> +            name: None,
Ah yeah that's fair, that makes sense.

2023-07-16 13:48 UTC, JakeStanger commented on src/ipc/server.rs
> +                    Response::error("Bar not found")
I think in this instance the fact that you're iterating over `application.windows()`, it's pretty clear what the type is going to be, so I don't have issue with that personally.

2023-07-16 13:52 UTC, JakeStanger requested changes

2023-07-16 13:52 UTC, JakeStanger commented on src/ipc/commands.rs
> +    /// Get the visibility of the specified window with the given name.
Please add whitespace between lines:

```suggestion

    /// Get the visibility of the specified window with the given name.
```

2023-07-16 13:52 UTC, JakeStanger commented on src/ipc/server.rs
> +                if let Some(window) = found {
Please add whitespace between lines:

```suggestion

                if let Some(window) = found {
```

2023-07-16 13:52 UTC, JakeStanger commented on src/ipc/server.rs
> +                if let Some(window) = found {
Please add whitespace between lines:

```suggestion

                if let Some(window) = found {
```

2023-07-16 13:52 UTC, JakeStanger commented on src/bar.rs
> +        .unwrap_or_else(|| format!("bar-{}", get_unique_usize()));
This clones the entire config just to get the name out, which wastes a lot of memory. Instead, pls just clone the name (`config.name.clone()`)

2023-07-16 13:53 UTC, JakeStanger commented
A couple of issues left from yesterday & a few more minor tweaks, but the implementation looks solid now. Cheers :)

2023-07-16 17:24 UTC, JakeStanger approved these changes

2023-07-16 17:35 UTC, merged