fix: properly parse properties in upower module
JakeStanger/ironbar pull request #441
Opened 2024-02-10 14:24 UTC by Disr0

Adds parsing in format for properties other than {percentages} :face_with_spiral_eyes:

2024-02-10 17:24 UTC, JakeStanger commented
Thanks for the PR. This is definitely a good addition. There are a few small bits that I think need addressing before this goes in:

This is a new feature, not a bug fix :) Could you amend your commit message to reflect that please so it gets added to the changelog correctly. Something like: `feat(upower): add new formatting properties`.

I don't think adding `icon_name` as a property is particularly helpful, unless there's something smart you could do with this and Pango? Otherwise it's sort of an internal identifier that gets exposed with little purpose.

Arguably the `time_to_empty` and `time_to_full` properties should be combined into one (perhaps just `time_remaining`?), which checks the state to see which underlying property to use. Otherwise you end up having to add both to have the ETA consistently display:

```corn
{ type = "upower" format = "{percentage}% {state} ({time_to_empty}{time_to_full})" }
```

I'm not sure whether the combine property should be instead of or in addition to the separated ones? Would people ever want to show one and not the other? I'm open to feedback on that one.

Once that's all done I'll re-review and update the docs page. Let me know if you need any help with any of the above :)

2024-02-10 17:32 UTC, JakeStanger requested changes
[Changes requested above]

2024-02-10 18:27 UTC, Disr0 commented
Yeah, ```icon_name``` isn't particularly useful, I'll remove it from the formatting.
Combining `time_to_empty` and `time_to_full` sounds more correct, yeah, but how should it be done? I'm not sure if adding `if` switch is a good idea, but maybe it's better than just concatenating `time_to_empty` and `time_to_full` as a string and sending it as `time_remaining`?

2024-02-10 18:49 UTC, yavko commented on src/modules/upower.rs
> +        7_u32..=u32::MAX => "Unknown",
Shouldn't this be `_ => "Unknown"` ?

2024-02-10 18:53 UTC, Disr0 commented on src/modules/upower.rs
> +        7_u32..=u32::MAX => "Unknown",
I based this on the enum description from here
https://docs.rs/upower_dbus/latest/upower_dbus/enum.BatteryState.html

2024-02-10 19:14 UTC, JakeStanger commented on src/modules/upower.rs
> +        7_u32..=u32::MAX => "Unknown",
Yeah good spot. It doesn't actually make any difference here, but the `7_u32..=u32::MAX` case could just be replaced with a catch-all `_` as it covers all other possibilities.

2024-02-10 19:17 UTC, Disr0 commented on src/modules/upower.rs
> +        7_u32..=u32::MAX => "Unknown",
Ah, I see

2024-02-10 19:43 UTC, yavko commented on src/modules/upower.rs
> +        7_u32..=u32::MAX => "Unknown",
> I based this on the enum description from here [docs.rs/upower_dbus/latest/upower_dbus/enum.BatteryState.html](https://docs.rs/upower_dbus/latest/upower_dbus/enum.BatteryState.html)

if thats the case you don't want to cast as an int:
```rs
match state {
        BatteryState::Unkown => "Unknown",
        BatteryState::Charging => "Charging",
        BatteryState::Discharging => "Discharging",
        BatteryState::Empty => "Empty",
        BatteryState::FullyCharged => "Fully charged",
        BatteryState::PendingCharge => "Pending charge",
        BatteryState::PedingDischarge => "Pending discharge",
        _ => "Unknown",
}
```

2024-02-10 19:45 UTC, yavko commented on src/modules/upower.rs
> +        7_u32..=u32::MAX => "Unknown",
This is so you get type checking if a new variant begins to exist

2024-02-10 20:22 UTC, JakeStanger commented on src/modules/upower.rs
> +        7_u32..=u32::MAX => "Unknown",
The client returns a `u32` and that gets mapped onto the `BatteryState` on an ad-hoc basis, so the casting is always `u32` -> `BatteryState`. Really this is a problem at the controller & `UPowerProperties` struct definition level. It might make sense to refactor that.

2024-02-10 20:39 UTC, yavko commented on src/modules/upower.rs
> +        7_u32..=u32::MAX => "Unknown",
Yeah, I see that now, https://github.com/JakeStanger/ironbar/pull/441/files#diff-6fb3d399ffa41e0be3e32a6faac7a73913a6f5a9759c6f6d28dd0345348a9e17R48 needs to be changed

2024-02-11 16:32 UTC, JakeStanger requested changes
Looking nearly there, cheers for your work on this. Just one minor adjustment I think, then I'm happy with it. 

Are you able to squash your commits down into a single one which matches the PR title? I can give a hand with that if not.

2024-02-11 16:32 UTC, JakeStanger commented on src/modules/upower.rs
> +            }
In Rust `if else` is actually an expression, so you can use it directly for assignment:

```suggestion
            let time_remaining = if is_charging {
                seconds_to_string(properties.time_to_full);
            }
            else {
                seconds_to_string(properties.time_to_empty);
            }
```

(I don't think that suggestion is `rustfmt` compliant so you'll probs need to run after applying)

2024-02-11 17:23 UTC, Disr0 commented on src/modules/upower.rs
> +            }
Sadly this doesn't work, as then the `time_remaining` variable will be of type `&()`

2024-02-11 17:31 UTC, JakeStanger commented on src/modules/upower.rs
> +            }
My bad - the semicolons make the difference there due to Rust's implicit returns. Updated.

2024-02-11 18:06 UTC, Disr0 commented on src/modules/upower.rs
> +            }
Implemented the change.

2024-02-11 23:20 UTC, JakeStanger approved these changes

2024-02-11 23:22 UTC, JakeStanger commented
Cheers, lgtm. I'll update the docs to add in the relevant section & merge in the next few days.

2024-02-12 23:14 UTC, merged