Add NetworkManager module
JakeStanger/ironbar pull request #518
Opened 2024-03-30 16:23 UTC by Zedfrigg

Implements a module displaying (very) basic network connectivity from NetworkManager.

2024-03-30 16:54 UTC, JakeStanger requested changes
Thanks for your hard work on this so far. There's a few changes needed here, but generally the code looks solid & this should be a good foundation for the module.

If you can also resolve the formatting issue, and squash commits down into one please that'd be great. 

Any questions let me know.

2024-03-30 16:54 UTC, JakeStanger commented on docs/modules/Networkmanager.md
> +which point it will display the latter. A solution to this is currently in the works.
It might be better to use a note block here, just so it's immediately clear to anybody reading the page.

```suggestion
> [!NOTE]
> This module uses NetworkManager's so-called primary connection, 
> and therefore inherits its limitation of only being able to display the "top-level" connection. 
> For example, if we have a VPN connection over a wifi connection it will only display the former, until it is disconnected, at which point it will display the latter. 
> 
> A solution to this is currently in the works.
```

2024-03-30 16:54 UTC, JakeStanger commented on src/config/mod.rs
> +use crate::modules::networkmanager::NetworkmanagerModule;
Can struct/enum casing be changed throughout please to `NetworkManager` to match the program name. The feature flag and module type can stay as-is though I think.

2024-03-30 16:54 UTC, JakeStanger commented on src/modules/networkmanager.rs
> +               proxies. */
I think this TODO needs resolving before anything is merged. A controller is spawned for every module instance, which means every instance (across every bar) creates another connection to DBus.

Agreed long-term the right solution is to use the trait-based approach. I'm not sure I understand your reasoning as of current though. 

It should be sufficient to wrap the client code as-is in its own struct, and just provide a `subscribe` method which returns a `broadcast::Receiver`. That's the pattern I've used elsewhere so there should be a good few examples if you need a pointer.

2024-03-30 16:54 UTC, JakeStanger commented on src/modules/networkmanager.rs
> +                    .path("/org/freedesktop/NetworkManager")?
These should be `const` values at the top of the func/module please

2024-03-30 16:54 UTC, JakeStanger commented on src/modules/networkmanager.rs
> +                .map(|provider| provider.load_into_image(icon.clone()));
Heads-up I do want to refactor how this works to resolve #511. For now though, this is fine.

2024-03-30 16:54 UTC, JakeStanger commented on src/modules/networkmanager.rs
> +        .unwrap();
Unwrap should be avoided in production code. Generally you should either handle the error, or use `expect` if you know it absolutely should not fail to state *why* it should not fail.

In this case, since you're returning `color_eyre`'s magic report, you can just use the `?` operator to propagate any errors up. Either that or fall back to a safe default (ie assume disconnected or unknown)

2024-04-18 11:59 UTC, Zedfrigg commented on src/modules/networkmanager.rs
> +               proxies. */
Alright, I've now rewritten the module to use a client. It overall matches the pattern you mentioned, with the exception that I've used a signal from `futures_signals` instead of a Tokio's `broadcast` to provide reactivity from the client to the module controller. Because a single `ClientState` instance contains everything the UI needs to render, there is no need to process previous values, just the latest.

Let me know what you think of this!

2024-04-18 11:59 UTC, Zedfrigg commented on src/config/mod.rs
> +use crate::modules::networkmanager::NetworkmanagerModule;
Implemented :+1:

2024-04-18 11:59 UTC, Zedfrigg commented on docs/modules/Networkmanager.md
> +which point it will display the latter. A solution to this is currently in the works.
Implemented :+1:

2024-04-18 12:01 UTC, Zedfrigg commented on src/modules/networkmanager.rs
> +        .unwrap();
This code has now been moved to `clients/networkmanager.rs`, where it now uses the `error!` plus `return` pattern used elsewhere.

2024-04-18 12:02 UTC, Zedfrigg commented on src/modules/networkmanager.rs
> +                    .path("/org/freedesktop/NetworkManager")?
Implemented :+1:

2024-04-18 12:05 UTC, Zedfrigg commented on src/clients/networkmanager.rs
> +        };
The error handling here is uhhh a bit verbose, but I couldn't think of a good way to replace it. If you have any suggestions for this I'd love to hear them.

2024-04-19 12:43 UTC, JakeStanger commented on src/clients/networkmanager.rs
> +        };
If you make `run` return a `Result<()>` (you can either use the ZBus Result type or `color_eyre::Result` if that proves a pain), you should be able to just use the question mark operator. 

```rs
let dbus_connection = Connection::system()?
let builder = PropertiesProxy::builder(&dbus_connection);
let builder = builder.destination(DBUS_BUS)?;

// etc...
```


I recently refactored some of the client code so that they can fail on startup - you should be able to see examples in the other dbus-based clients.

2024-04-19 14:27 UTC, JakeStanger commented on src/modules/networkmanager.rs
> +               proxies. */
I've not seen `futures_signals` before. It looks powerful but I'm interested as to what it brings in that a broadcast channel doesn't. Does `futures_signals` always return the current state on the first call to `next()`, in order to initialise?

2024-04-19 15:12 UTC, Zedfrigg commented on src/modules/networkmanager.rs
> +               proxies. */
Yes, basically if the `Mutable` in the client is updated more than once, followed by a read of its signal through `next()`, that read will only see the most recent value. This is of course fairly useless for communicating events (essentially changes to state), because we need to process all of them in order to arrive at the new state. But because it's much simpler to just communicate the entire new state (`ClientState`) to the module instances, we don't need a queue, just the latest value. Also see [the docs](https://docs.rs/futures-signals/latest/futures_signals/tutorial/index.html).

Of course, if you don't want to pull in the extra dependency I can rewrite it in terms of a `broadcast` queue, at the cost of some performance.

As for your second question, yes, all the module instances receive the update - as long as they call `subscribe` of course.

2024-04-22 13:58 UTC, Zedfrigg commented on src/clients/networkmanager.rs
> +        };
Excellent timing with that refactor :ok_hand: 

I've rewritten things accordingly, and it's looking a lot nicer now, thanks.

2024-04-29 21:44 UTC, Zedfrigg commented
@JakeStanger let me know if you think the code is ready to merge in its current state :)

2024-05-01 19:48 UTC, JakeStanger requested changes
It's getting there generally, but there's still a few things pending  & I'm still not 100% sure about the signals crate - if you can get back to my Qs pls just to clear up some potential concerns.

I need to give this a proper test too, so I'll try and do that as soon as I can.

2024-05-01 19:48 UTC, JakeStanger commented on src/modules/networkmanager.rs
> +use gtk::{Box, Image, Orientation};
I'm not a fan of importing `gtk::Box` because it makes it harder to use the stdlib Box type.

2024-05-14 17:12 UTC, Zedfrigg commented on src/modules/networkmanager.rs
> +use gtk::{Box, Image, Orientation};
Fair enough, I aliased them as `GtkBox` now

2024-05-14 17:15 UTC, Zedfrigg commented on src/clients/networkmanager.rs
> +        };
Yes, see [here](https://people.freedesktop.org/~lkundrak/nm-docs/gdbus-org.freedesktop.NetworkManager.html)

2024-05-14 17:37 UTC, Zedfrigg commented on src/modules/networkmanager.rs
> +               proxies. */
Yeah, we could either choose to put them in various structs that then get nested in each other, or have multiple `Mutable`s, each for a distinct part of the state. Either approach will work. For communication back from the widget to the client, we'll stick with the events on a `tokio::sync::broadcast` model.

2024-05-29 20:43 UTC, JakeStanger commented on src/clients/networkmanager.rs
> +        };
I hate DBus :) Got to be the worst syntax for showing type info ever conceived. 

I was initially wondering if a macro would help reduce the boilerplate here, but not sure if it will actually?

2024-05-29 20:44 UTC, JakeStanger commented on src/modules/networkmanager.rs
> +               proxies. */
Okay, that sounds good to me then, happy to stick with that.

2024-05-30 17:07 UTC, Zedfrigg commented on src/clients/networkmanager.rs
> +        };
What will definitely help with that is switching to using proxy traits. I should get around to doing that refactor...

As a tangent, I also like how the zbus crate does it. They take a different approach and just infer everything from the Rust type of the variable you assign it to.

2024-06-05 11:16 UTC, Zedfrigg commented on src/clients/networkmanager.rs
> +        };
Update: I've now done that refactor and the code is indeed now looking a lot nicer.

2024-06-05 20:46 UTC, JakeStanger commented on Cargo.toml
> +schemars = { version = "0.8.21", optional = true }
I intentionally added this one to the bottom as it's not a 'standard' module feature

2024-06-05 20:52 UTC, JakeStanger commented on src/modules/networkmanager.rs
> +pub struct NetworkManagerModule {
The introduction of JSON schema support annoyingly means every type used in the config needs to derive the `JsonSchema` type when the feature is enabled:

```suggestion
#[derive(Debug, Deserialize, Clone)]
#[cfg_attr(feature = "schema", derive(schemars::JsonSchema))]
pub struct NetworkManagerModule {
```

2024-06-05 20:53 UTC, JakeStanger requested changes
Thanks for the work on the refactor, and apologies I haven't inputted a lot on this one for a while.

A couple of very small changes now, but outside of those the code lgtm now. I'll give this some tests and report back.

Is there anything else you want to add at the PR at this stage, or do you reckon we're go for the initial version?

2024-06-05 21:10 UTC, JakeStanger commented
> I'll give this some tests and report back.

Looks like it's all working as intended. I've tested Ethernet and Wifi and toggling connections in both cases causes instant updates.

2024-06-07 09:26 UTC, Zedfrigg commented on Cargo.toml
> +schemars = { version = "0.8.21", optional = true }
Oh I see! Moved it back now :+1:

2024-06-07 09:28 UTC, Zedfrigg commented on src/modules/networkmanager.rs
> +pub struct NetworkManagerModule {
Added it :+1:

2024-06-07 09:29 UTC, Zedfrigg commented
> Is there anything else you want to add at the PR at this stage, or do you reckon we're go for the initial version?

No as far as I'm concerned we're good to go!

2024-06-28 22:48 UTC, JakeStanger commented
Sorry for delay on this (again). There's a merge conflict outstanding - if you can resolve that I'll add the docs and merge :)

2024-06-30 15:48 UTC, Zedfrigg commented
Merged and re-tested :+1:

The `devShell` CI workflow is failing, but I don't think it's related to this change?

2024-08-04 11:59 UTC, JakeStanger approved these changes
Apologies for the huge delay on this, and thanks again for all your work. I've finally got round to putting the finishing touches on it.

FYI, I've made some basic refactors and renamed the module/feature flag to `network_manager`.

I'll merge this in a few mins and it'll be available in the git build.

2024-08-04 12:01 UTC, merged