feat: add man pages and shell completions
JakeStanger/ironbar pull request #683
Opened 2024-07-30 18:30 UTC by donovanglover

Auto-generated with clap.

Note: May be ideal to replace some of the sub-commands with flags to decrease the amount of generated man pages.

2024-08-10 23:18 UTC, donovanglover commented
Upstream issue: https://github.com/clap-rs/clap/issues/5337

Could add shell completions now and think about man pages later.

Long-term could auto-complete bar names and other information as well.

2024-11-04 13:25 UTC, JakeStanger requested changes
Thanks for your work here, this will be a great QoL improvement to have. Looking like it's most of the way there already.

I'll be looking to merge this as part of the 0.17.0 release as 0.16.1 will be bugfixes only.

2024-11-04 13:25 UTC, JakeStanger commented on build.rs
> +    Man::new(cmd.clone()).render(&mut buffer).unwrap();
I appreciate this is just a build script, but I'd still prefer to keep `unwrap`s out of the code pls. I'll be more lenient than usual towards using `expect` everywhere so long as it's clear why it *shouldn't* crash.

2024-11-04 13:25 UTC, JakeStanger commented on src/cli.rs
What's the reason for the restructuring here and moving `handle_response`? It looks like the diff has gone funny, so I'm assuming this isn't entirely intentional?

2024-11-07 16:59 UTC, donovanglover commented on src/cli.rs
I think this was to avoid unused code warnings from `build.rs`

2024-11-07 17:07 UTC, donovanglover commented
Unfortunately I doubt I'll have time to work on this anytime soon but you're free to change anything as needed. Should also avoid duplicate code from `src/ipc/commands.rs`.

2024-11-07 18:40 UTC, JakeStanger commented
No worries, thanks for the heads up. I'm happy to take it from here, appreciate the work you've done to get it this far.

2024-12-28 15:46 UTC, JakeStanger commented
I'm going to drop manpage support for now because I see it having pretty limited use, especially when `ironbar --help` provides a much more ergonomic interface to see the same information. Having every subcommmand as its own page sorta sucks, and I don't like the idea of changing the CLI interface to fit it.

The completion is already useful though, so I'll merge that.

2024-12-28 19:02 UTC, donovanglover commented
Sounds good to me. Thanks for working on this!

2024-12-29 00:24 UTC, JakeStanger approved these changes

2024-12-29 00:24 UTC, merged

2024-12-29 00:25 UTC, JakeStanger commented
Thanks for getting it started :)