Support For Niri Workspaces
JakeStanger/ironbar pull request #726
Opened 2024-09-08 17:56 UTC by anant-357

Hi, please let me know if I've missed something. Addresses #650.

2024-09-09 05:51 UTC, YaLTeR reviewed
Hi, only commenting on the niri IPC parts. I also clarified these in niri-ipc docs.

2024-09-09 05:51 UTC, YaLTeR commented on src/clients/compositor/niri.rs
> +                reference: WorkspaceReferenceArg::from_str(name.as_str()).unwrap(),
Since most workspaces don't have names, this should instead focus by Id (not Idx). There's `WorkspaceReferenceArg::Id(u64)`.

2024-09-09 05:51 UTC, YaLTeR commented on src/clients/compositor/niri.rs
> +            match conn.send(Request::Workspaces).await.unwrap().0.unwrap() {
You shouldn't need this. The event stream always sends the full initial workspaces state at the start.

2024-09-09 05:51 UTC, YaLTeR commented on src/clients/compositor/niri.rs
> +                                match old_workspace.id.cmp(&new_workspace.id) {
I'm not entirely sure if this code relies on this, but you probably shouldn't rely on workspace id increasing incrementally and never wrapping back. That is an implementation detail subject to change if needed.

2024-09-09 06:26 UTC, anant-357 commented on src/clients/compositor/niri.rs
> +                reference: WorkspaceReferenceArg::from_str(name.as_str()).unwrap(),
The focus method in the ```WorkspaceClient``` trait sends a name. So I would need some way to get the id from name. When converting from Niri Workspace struct to Ironbar Workspace struct, if the workspace has no name I set the id as name. Should I change the ```FromStr for WorkspaceReferenceArg``` to parse id instead of idx?

2024-09-09 06:32 UTC, YaLTeR commented on src/clients/compositor/niri.rs
> +                reference: WorkspaceReferenceArg::from_str(name.as_str()).unwrap(),
It depends on what ironbar gives you, which I'm not familiar with. Index will work only if the correct monitor is focused when you send this request.

2024-09-09 06:32 UTC, anant-357 commented on src/clients/compositor/niri.rs
> +                                match old_workspace.id.cmp(&new_workspace.id) {
What would be a better way of checking for all changes? I am also sorting both workspace states before comparing ids.

2024-09-09 07:45 UTC, anant-357 commented on src/clients/compositor/niri.rs
> +                                match old_workspace.id.cmp(&new_workspace.id) {
Ironbar has events like ```WorkspaceUpdate::Add(Workspace)``` and ```WorkspaceUpdate::Remove(id)``` so I cannot directly replace the workspace state. I will have to track changes from previous state.

2024-09-11 09:04 UTC, JakeStanger commented on src/clients/compositor/niri.rs
> +                reference: WorkspaceReferenceArg::from_str(name.as_str()).unwrap(),
I think it uses name because that was necessary for one of Sway or Hyprland. Using ID is definitely preferable. If necessary, I'd be okay splitting into a `FocusById` and `FocusByName` and letting each compositor impl pick the best case.

2024-09-11 09:08 UTC, JakeStanger commented on src/clients/compositor/niri.rs
> +                                match old_workspace.id.cmp(&new_workspace.id) {
What does the `WorkspacesChanged` event signify in Niri? Is it just any addition/removal/rename/move?

2024-09-11 09:10 UTC, JakeStanger commented
Appreciate the hard work here, big thanks for taking this on. Cheers YaLTeR for reviewing too, means a lot to see the actual dev provide input. 

I'm a little busy at the moment so responses from me won't be as fast as I like, but ping me as soon as you need anything from me and I'll look as soon as I can. I'll give it a full review as soon as you're ready.

2024-09-11 09:15 UTC, YaLTeR commented on src/clients/compositor/niri.rs
> +                                match old_workspace.id.cmp(&new_workspace.id) {
It signifies the new complete workspaces state. Anything could change. Basically an escape hatch event for changes not covered by other events, or when multiple things need to change at once. In practice, workspace additions/removals/reorders all use this because it would be too complex to handle them as separate events atomically.

2024-09-11 09:26 UTC, JakeStanger commented on src/clients/compositor/niri.rs
> +                                match old_workspace.id.cmp(&new_workspace.id) {
Right okay. So the cheap and dirty way of handling that on Ironbar's side would be to slightly adjust and reuse the `WorkspaceUpdate::Init` event, which takes the full state. The issue I have with that is that it's very expensive to dump and re-render the UI every time anything changes.

Tracking state changes on Ironbar's side *is* preferable, if not possible in Niri. At least for the cases where we can.

2024-09-11 09:32 UTC, YaLTeR commented on src/clients/compositor/niri.rs
> +                                match old_workspace.id.cmp(&new_workspace.id) {
In my Waybar PR I did a sequence of remove obsolete widgets, add new widgets, reorder all to update positions on a vector of workspaces pre-sorted by idx.

2024-09-11 11:08 UTC, anant-357 commented on src/clients/compositor/niri.rs
> +                                match old_workspace.id.cmp(&new_workspace.id) {
The way I am handling this here is by keeping a previous state of workspaces and comparing with the new state for changes. To do this, first I sort both(old and new) workspace vectors based on id. Then I do a linear scan on the states at together. If the id is missing, then I send a ```WorkspaceUpdate::Remove``` event. If there is a new id then I send a ```WorkspaceUpdate::Add``` event. For workspaces with the same id, if the name of the workspace is different, ```WorkspaceUpdate::Rename``` is sent, if the name of the monitor is different then ```WorkspaceUpdate::Move``` is sent.

2024-09-18 10:06 UTC, JakeStanger requested changes
I'm yet to test the PR, but generally this is looking good. There's a few points after an initial scan I'd like addressed, but nothing major. Thanks again for your hard work.

2024-09-18 10:06 UTC, JakeStanger commented on src/clients/compositor/niri.rs
> +                std::thread::sleep(Duration::from_millis(30));
As you are inside an async block, you should use Tokio's sleep to avoid blocking the thread.

2024-09-18 10:06 UTC, JakeStanger commented on src/clients/niri.rs
As this is all compositor-focused I would prefer if all this code was under the `compositor` module for now. Happy to have a `niri` module with a couple of files in there.

2024-09-18 10:06 UTC, JakeStanger commented on src/clients/niri.rs
> +        let mut buf = serde_json::to_string(&request).unwrap();
In cases like this, if you return a `color_eyre::Result` you should be able to automatically use the `?` operator despite mixing error types.

2024-11-12 23:00 UTC, JakeStanger requested changes
Looking like the code is almost there, thanks for your work & sorry it's taken me so long to have a look. I'll try and test soon so that we can get this in relatively quick for 0.17.0.

2024-11-12 23:00 UTC, JakeStanger commented on src/clients/compositor/niri/mod.rs
> +                    reference: WorkspaceReferenceArg::from_str(name.as_str()).unwrap(),
Please can this unwrap be changed. By the looks of it this is infallible so just need to say it should always be valid in an `expect`.

2024-11-12 23:00 UTC, JakeStanger commented on src/clients/compositor/niri/mod.rs
> +                                                        workspace_state[new_index].visibility =
There are a lot of lookups to to `workspace_state[new_index]` and `workspace_state[old_index]` throughout this block. Could these just be referenced as `new` and `old` variables pls to clean up a bit.

2024-11-12 23:00 UTC, JakeStanger commented on src/clients/compositor/niri/mod.rs
> +                            }
Is there a risk of filling up the channel buffer here by sending too many events at once? Some stress testing may be required to check. If it is a potential problem, a 'batch' event might solve it.

2024-11-14 17:09 UTC, anant-357 commented on src/clients/compositor/niri/mod.rs
> +                                                        workspace_state[new_index].visibility =
I cannot have 2 mutable borrows from the ```workspace_state``` . Is there a particular way of doing this?

2024-11-19 10:23 UTC, calops commented on src/clients/compositor/niri/mod.rs
> +                                                        workspace_state[new_index].visibility =
I tried to address this point on my side and it really messes up the code for no clear benefit. I think it's better to leave it like this.

2024-11-19 10:24 UTC, calops commented
Hi there! Thanks for the work, this PR is exactly what I need. Is there anything I can do to help move it forward?

2024-11-19 10:36 UTC, JakeStanger commented on src/clients/compositor/niri/mod.rs
> +                                                        workspace_state[new_index].visibility =
Thought that'd probs be the case, happy to leave as-is then. Cheers for checking on behalf

2024-11-19 11:02 UTC, JakeStanger commented
Hey, the following are outstanding:

- [ ]  Any unresolved comments here
- [ ] Documentation updates
  - [ ] README - we now offer first-class support for Niri
  - [ ] Workspaces - module now supports Niri
- [ ] Testing

If you're able to offer a hand with any of the above at all, that'd be great. 

The plan is to ship 0.16.1 this weekend, assuming the tray doesn't find new ways to break before then. Once that's out, I'll merge this as soon as it's ready.

2024-11-19 11:34 UTC, anant-357 commented
There is an issue. If I remove a workspace from the middle, somehow when I move to another workspace, the focused workspace on the bar does not change. I am unable to pin point why this is happening. I also do not have multiple monitors, so it would be helpful if anyone could test for that.

2024-11-19 12:16 UTC, calops commented
I'd love to tackle these issues, but I don't know the best way to do it on a PR that comes from a fork that I don't own.

And for the comment about stress testing, I'm also not sure how to go about this.

2024-11-19 13:14 UTC, JakeStanger commented
You may be able to open a PR on the fork, targeting the branch used for this PR. If that gets merged, it'll update here. If not you can just send a file.

Spamming the Niri IPC (aka a while true loop) with workspace changes and ensuring Ironbar can keep up is sufficient for stress testing.

2025-02-18 22:50 UTC, JakeStanger commented
I'm closing in favour of #871, so I can rebase and continue development to get this across the line, as this being on the master branch with merge commits makes that difficult. You'll still be credited.

As it stands, that PR is identical to this one, albeit rebased onto the latest master commit and squashed.

2025-02-18 22:50 UTC, closed without merging