feat: Minimize focused window option for launcher
JakeStanger/ironbar pull request #769
Opened 2024-11-10 06:24 UTC by pachliopta

This PR adds a new config option `minimize_focused` to the launcher module, which when set to true will minimize the currently focused window if its icon is clicked. If there is more than a single window open of that particular application the normal focus behavior will occur.

I haven't written much rust before, but hopefully it's relatively problem free!

Resolves  #658

2024-11-10 13:39 UTC, JakeStanger commented on src/modules/launcher/mod.rs
> +    #[serde(default = "crate::config::default_false")]
I reckon this should actually be on by default

2024-11-10 13:44 UTC, JakeStanger commented on src/modules/launcher/mod.rs
> +                    let mut minimize_window = false;
I think it'd be slightly cleaner to calculate this in-place, like:

```suggestion
                    let mut minimize_window = false;
                    let minimize_window = matches!(event, ItemEvent::MinimizeItem(_));
```

(untested but I think that should work)

2024-11-10 13:45 UTC, JakeStanger commented on src/modules/launcher/mod.rs
> +                        ItemEvent::FocusItem(app_id) => search_items(app_id),
Based on the prev comment, that would allow you to combine the focus/minimize branches here:

```suggestion
                        ItemEvent::FocusItem(app_id) => search_items(app_id),
                        ItemEvent::FocusItem(app_id) | ItemEvent::MinimizeItem => search_items(app_id),
```

2024-11-10 13:47 UTC, JakeStanger requested changes
Thanks for this, this all looks great. I've raised a few minor points if you could have a look at those please.

I will be looking at merging this for 0.17, as soon as 0.16.1 is released.

2024-11-10 15:10 UTC, pachliopta commented on src/modules/launcher/mod.rs
> +                        ItemEvent::FocusItem(app_id) => search_items(app_id),
Makes sense! I wanted them on the same branch but I preoccupied myself hoping for some esoteric solution that just doing it in place never crossed my mind

2024-11-10 15:10 UTC, pachliopta commented
Changes should be addressed now, thank you for taking a look!

2024-11-10 16:55 UTC, JakeStanger reviewed
lgtm, cheers. I'll give a quick test when I can & approve when confirmed working.

2024-11-24 21:47 UTC, JakeStanger approved these changes

2024-11-24 21:49 UTC, merged