Allow IPC to act on multiple bars by the same name
JakeStanger/ironbar pull request #777
Opened 2024-11-12 22:23 UTC by zeroeightysix

Closes #770

2024-11-13 10:39 UTC, JakeStanger requested changes
Thanks for this. I've flagged some changes I think should go in first. Please also ensure the styling is fixed.

Documentation will also need updating - are you happy to take this on?

2024-11-13 13:49 UTC, zeroeightysix commented
> Documentation will also need updating - are you happy to take this on?

Sure! To make sure I don't miss anything, where are the places I should be looking?

2024-11-13 23:16 UTC, JakeStanger commented
It should just be the [Controlling Ironbar](https://github.com/JakeStanger/ironbar/wiki/controlling-ironbar) page

2024-11-15 23:44 UTC, JakeStanger commented on src/ipc/server/bar.rs
> +        .collect::<Vec<_>>();
As you're immediately iterating over the responses, it'd be better to avoid collecting & allocating a vec, and instead tag the below `reduce` on straight after the map

2024-11-15 23:45 UTC, JakeStanger commented on src/ipc/server/bar.rs
> +        .unwrap()
Please avoid `unwrap`. It looks like here there's no possible path for the program to panic, so instead use `expect` & explain why

2024-11-15 23:45 UTC, JakeStanger requested changes
Cheers for changes, just a couple of little bits more when you can pls

2024-11-16 20:11 UTC, zeroeightysix commented on src/ipc/server/bar.rs
> +        .unwrap()
Although slightly complicating the flow, I might as well use `unwrap_or` and remove the length check at the beginning

2024-11-16 20:40 UTC, JakeStanger reviewed
Perfect, thanks, code LGTM. I'll test shortly & approve if all seems good!

2024-11-16 20:46 UTC, JakeStanger approved these changes

2024-11-16 20:48 UTC, merged