implement upower module
JakeStanger/ironbar pull request #83
Opened 2023-03-18 21:09 UTC by p00f

There are a couple of issues:

1) I want to use the popup to show additional details like time to empty/full and battery levels of other connected devices like bluetooth headphones. I've hardcoded the function for now but nothing happens when I click the module

2) upower will tell me what icon to use depending on battery level and whether it is plugged in, how do I implement this? I did `    format: "icon:{icon} {percentage}%"` in config.yaml but that doesn't seem to work

![image](https://user-images.githubusercontent.com/36493671/226140221-8302d51d-a24d-4331-9c4f-199e6d552f83.png)

Broadly it seems to work fine

2023-03-18 21:10 UTC, p00f commented
@JakeStanger pinging you because I don't think you get notified of draft prs

2023-03-18 21:32 UTC, JakeStanger commented
I do get notified actually :)

1. You need a `gtk::Button` inside the widget which sends an open command on click. See how I'm doing it here:
https://github.com/JakeStanger/ironbar/blob/d4dd8c41ea54575173f045740991d8ff0e735211/src/modules/clock.rs#L68-L74

2. It looks like upower just returns the name and there's aren't actually attached to icons anywhere, but rather left to the implementer (that's us!). I would suggest adding a map into the config option like `music` does https://github.com/JakeStanger/ironbar/blob/d4dd8c41ea54575173f045740991d8ff0e735211/src/modules/music/config.rs#L79-L81 and then using an icon label https://github.com/JakeStanger/ironbar/blob/d4dd8c41ea54575173f045740991d8ff0e735211/src/modules/music/mod.rs#L454 to let users choose any text/gtk icon/image they want. You can then pick some sensible defaults from [nerd fonts](https://www.nerdfonts.com/cheat-sheet). This implementation does mean you cannot add the icon to the formatting, and instead it will need to be hard-coded to the start/end, but I think that's fine.

I appreciate that's fairly involved, so give me a heads up if you get stuck.

2023-03-19 04:02 UTC, p00f commented
The name of the icon is an actual icon in adwaita so I wanted to just pick that icon instead of making it configurable, this is what waybar does as well

2023-03-19 11:53 UTC, JakeStanger commented
Ah okay, that's handy. I think most of the above still applies. You can use `new_icon_label` and pass it the icon name prefixed with `icon:` (so like `icon:battery-good-charging-symbolic`) and it will automatically resolve the image from the icon theme for you. That also means it could be configurable to override the theme default in the future.

2023-04-16 02:14 UTC, yavko commented
Is there anything blocking the merge of this? If help is needed, I can help out. I would love to see this in ironbar!

2023-04-16 05:39 UTC, p00f commented
@yavko I can't get icons to work

2023-04-16 10:41 UTC, JakeStanger commented
Feel free to push your latest version up (might be wise to rebase onto master to get the latest changes) and I can have a look :)

2023-04-16 11:01 UTC, p00f commented
The conflict is in Cargo.lock which I'm not sure how to handle, I haven't worked on this after the last push

2023-04-16 11:04 UTC, JakeStanger commented
So long as the cargo.toml is fine, you can do whatever with the merge, then just delete cargo.lock and regen to ensure it generates a new valid lock. 

I'm not sure if that's necessarily best practise but it's the easy way lol - I'll just double check it when we get to review stage.

2023-04-16 11:13 UTC, p00f commented
@JakeStanger done

2023-04-16 11:15 UTC, p00f commented
oh sorry it doesn't compile

2023-04-16 11:18 UTC, p00f commented
fixed it

2023-04-16 12:48 UTC, JakeStanger commented
Now I'm looking at it, using `new_icon_label` here is a bit more fiddly than I would have liked, so might not be the best path. Luckily it's fairly simple so we can replicate the needed behaviour in a few lines.

What you should able to do here instead is create an image widget and add it to your container:

```rs
let icon = gtk::Image::new();
// ...set up/add widget...
```

Then inside your callback where you get the icon name, you can pass it (still in the `icon:name` format) to `ImageProvider::parse` to load the new icon into your image widget.

```rs
if let Err(err) = ImageProvider::parse(input, icon_theme, size)
            .and_then(|provider| provider.load_into_image(icon) {
    error!("{err:?}");
}
```

I'd advise caching the previous icon name to avoid re-loading the same image over and over, but we can get to bits like that when you're ready for a full review.

2023-04-20 21:42 UTC, JakeStanger requested changes
Thanks for all the work so far, it's really appreciated. This is looking generally very good so far :)

Most of the bits I've raised are trivial pedantic bits, but there's a couple of more complex issues so do let me know if you need a hand with any of those.

The build is failing currently due to compiler errors when `--no-default-features` is set. One of the reasons is because `regex` is behind a feature flag, but it looks like that's not actually needed here anyway. The other is due to the incomplete icon code, so that should resolve itself in time.

2023-04-20 21:42 UTC, JakeStanger commented on Cargo.toml
> +default = ["http", "config+all", "clipboard", "clock", "music+all", "sys_info", "tray", "workspaces+all"]
Can this be on multiple lines as it was please? 

Also can you add a `upower` feature flag that enables the new dependencies (enabled by default)?

2023-04-20 21:42 UTC, JakeStanger commented on Cargo.toml
> +futures-lite = "1.12.0"
Please move these out of the shared section into a new `upower` section above.

2023-04-20 21:42 UTC, JakeStanger commented on src/bar.rs
> +            ModuleConfig::Upower(mut module) => add_module!(module, id),
Please move this above `Workspaces` to keep them in alphabetical order.

2023-04-20 21:42 UTC, JakeStanger commented on src/config/mod.rs
> +    Upower(Box<UpowerModule>),
Please move this below `Tray` to keep them in alphabetical order.

2023-04-20 21:42 UTC, JakeStanger commented on src/modules/upower.rs
> +    type SendMessage = HashMap<String, OwnedValue>;
Since you are only consuming a few properties, it would be better to use a custom struct with just the consumed fields rather than a hashmap. 

This removes the need to send the whole properties object across the channel, and also means you can handle the processing (ie the type downcasting) in the controller.

2023-04-20 21:42 UTC, JakeStanger commented on src/modules/upower.rs
> +                .await?;
Since `spawn_controller` runs for every module instance, this could spawn a lot of DBus connections. For other clients I've gone about this by creating a client struct in the clients module, and then wrapped it with `lazy_static`  and `AsyncOnce` to create a singleton instance.

The client struct then has a broadcast channel that the controller can subscribe to, in order to receive events. These can then be processed and sent to the module. See the tray as an example:
https://github.com/JakeStanger/ironbar/blob/8e99fd4d0f01cf4406cabf19fb635f03447753c8/src/clients/system_tray.rs#L96-L124

That can be quite fiddly so let me know if you need a hand.

2023-04-20 21:42 UTC, JakeStanger commented on src/modules/upower.rs
> +    time_string
I think this could cause trailing spaces. For example if you have 0 days, it will start with eg " 3h". I think a trim will be sufficient to sort that.

2023-04-20 21:42 UTC, JakeStanger commented on src/modules/upower.rs
> +        let percentage_re = Regex::new(r"\{percentage}")?;
Since these are checking exact matches, you can just use `.contains()` on the string.

2023-04-20 21:42 UTC, JakeStanger commented on src/modules/upower.rs
> +fn u32_to_batterystate(number: u32) -> Result<BatteryState, u32> {
This can be made constant:

```suggestion
const fn u32_to_batterystate(number: u32) -> Result<BatteryState, u32> {
```

2023-04-20 21:42 UTC, JakeStanger commented on src/modules/upower.rs
> +    use BatteryState::*;
I'm not a huge fan of the wildcard enum import (and neither is pedantic clippy). Could you remove this and qualify the enums please?

2023-04-20 21:42 UTC, JakeStanger commented on src/modules/upower.rs
> +                    .unwrap();
There are a few calls to `unwrap()` throughout. Can these be changed please:

- If it is a situation that should not occur under any scenario (ie indicates a severe bug), use `expect` and pass a clear message as to what went wrong.
- If it could error, please handle the error either by logging it or falling back appropriately.

2023-04-21 18:07 UTC, p00f commented
the icon is wrong:
![image](https://user-images.githubusercontent.com/36493671/233704820-b995690e-f0fb-4a1c-aab6-5f2e87068446.png)

2023-04-21 21:13 UTC, JakeStanger commented
I don't have a device with a battery that I can test this against, but on my desktop the correct `battery-missing-symbolic` icon is showing.

2023-04-21 21:15 UTC, JakeStanger commented on src/modules/upower.rs
> +    format: String,
Please add a default serde value for format.

2023-04-21 21:17 UTC, JakeStanger commented on Cargo.toml
> +    "upower"
Pedantry regarding the ordering again, but please swap these two around

2023-04-21 21:18 UTC, JakeStanger commented on src/modules/mod.rs
> +pub mod upower;
This should have a cfg attr:

```suggestion
#[cfg(feature = "upower")]
pub mod upower;
```

2023-04-21 21:18 UTC, JakeStanger commented on src/config/mod.rs
> +use crate::modules::upower::UpowerModule;
This should have a cfg attr:

```suggestion
#[cfg(feature = "upower")]
use crate::modules::upower::UpowerModule;
```

2023-04-21 21:22 UTC, JakeStanger requested changes
A few more little bits, but looking like it's nearly there! Let me know when you've got these, and the few changes leftover from yesterday sorted, thanks!

2023-04-22 02:19 UTC, p00f commented
should i retry if connecting to the system bus (or anything in the dbus initialization portion) fails?

2023-04-22 02:37 UTC, p00f commented
the icon was fine, it was just black on black.

2023-04-22 09:50 UTC, JakeStanger commented
> should i retry if connecting to the system bus (or anything in the dbus initialization portion) fails?

I don't think so. I think if DBus ever fails to connect, that's a much greater problem that retrying probably won't fix, so the best action is probably to just log the error and exit (expect is probably fine in that case)

2023-04-22 15:15 UTC, JakeStanger commented on src/modules/upower.rs
> +        let percentage_re = Regex::new(r"\{percentage}")?;
Please remove this regex - you can just use `.contains()`

2023-04-22 15:17 UTC, JakeStanger commented on src/modules/upower.rs
> +                                .expect("expected Percentage to be f64")
```suggestion
                                .expect("expected Percentage to be f64");
```

2023-04-22 15:18 UTC, JakeStanger commented on src/modules/upower.rs
> +            let state: BatteryState = u32_to_batterystate(properties.state).unwrap();
Please replace this unwrap

2023-04-22 15:20 UTC, JakeStanger requested changes
Couple of tiny bits left, then I think it's just about there :)

2023-04-23 21:45 UTC, yavko commented
I just wanted to comment, I see you are using the icon from `upower`, which makes sense, but honestly, I think the icon it gives it pretty misleading sometimes, I know this is extra code, but it provides a more accurate icon, in case you want to see how I did it in the past. Not sure if this icon is in all icon packs, but after checking seems it's in papirus and adwaita, and breeze too, it just has a leading zero on all the numbers, so actually maybe this isn't the best idea, as it'd have to be checked at runtime. (also, this was written with an older version of `upower_dbus`, so I don't know if `BatteryState` still exists, or works the same)

```rs
fn get_icon_name(status: BatteryState, capacity: u64) -> String {
    let suffix = if status == BatteryState::Charging {
        "-charging"
    } else {
        ""
    };

    let cap: u8 = match capacity {
        0..=9 => 0,
        10..=19 => 10,
        20..=29 => 20,
        30..=39 => 30,
        40..=49 => 40,
        50..=59 => 50,
        60..=69 => 60,
        70..=79 => 70,
        80..=89 => 80,
        90..=99 => 90,
        100 => 100,
        _ => 0,
    };

    format!("battery-level-{cap}{suffix}-symbolic")
}
```

2023-04-29 22:32 UTC, JakeStanger commented
@p00f Thanks for all your work. I'm gonna complete the last few bits & add the docs, then get this merged.

@yavko That sounds good to me. I'll merge the current implementation for now, but if you want to follow up with a PR that adds your icon method, falling back to the upower icon if it's not present in the theme, that would be fantastic (if not that's cool too ofc, I'll add it to the todo list)

2023-04-29 23:26 UTC, merged